- name: NGINX | repo
  yum:
    name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
 
- name: NGINX | yum
  yum:
    name: nginx
    state: latest

- name: be sure libselinux-python are installed or nginx file copies fail
  yum:
     name: libselinux-python
     state: present

- name: NGINX | config file 
  copy: src=../nginx/nginx.conf dest=/etc/nginx/nginx.conf
- name: NGINX | server file 
  copy: src=../nginx/default.conf dest=/etc/nginx/conf.d/default.conf

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started
    enabled: yes
