- name: NGINX | repo
  yum:
    name: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
 
- name: NGINX | yum
  yum:
    name: nginx
    state: latest

- name: NGINX | config files 
  copy: src=../nginx/nginx.conf dest=/etc/nginx/nginx.conf
  copy: src=../nginx/default.conf dest=/etc/nginx/conf.d/default.conf

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started
    enabled: yes


- name: NGINX | copy app
  copy: src=../app.php dest=/usr/share/nginx/html/app.php
